export interface PatchHistoryEntry {
  readonly hash: string
  readonly date: string
  readonly author: string
  readonly subject: string
}

export const PATCH_HISTORY_CAPTURE = {
  commitCount: 160,
  firstDate: "2026-08-12",
  lastDate: "2026-08-25",
  branch: "preview/single-screen-rag-desk",
  head: "8251f6e",
} as const

export const PATCH_HISTORY: readonly PatchHistoryEntry[] = [
  { hash: "a582be5", date: "2026-08-12", author: "Fare Estimator", subject: "feat: establish tested RAG domain foundation" },
  { hash: "5ad5111", date: "2026-08-12", author: "Fare Estimator", subject: "test: define persistence and ingestion safety contracts" },
  { hash: "1d68547", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add immutable corpus persistence contracts" },
  { hash: "f73c0e8", date: "2026-08-12", author: "Fare Estimator", subject: "test: define grounded Responses API behavior" },
  { hash: "cd86b49", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add grounded Responses API adapter" },
  { hash: "e3ab650", date: "2026-08-12", author: "Fare Estimator", subject: "test: define authenticated API boundary" },
  { hash: "6caf31b", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add authenticated FastAPI contract" },
  { hash: "e5f069d", date: "2026-08-12", author: "Fare Estimator", subject: "test: define local runtime and migration contracts" },
  { hash: "e4b2462", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add reproducible Python and Postgres runtime" },
  { hash: "eb84e93", date: "2026-08-12", author: "Fare Estimator", subject: "test: define Postgres atomicity and ownership guarantees" },
  { hash: "8ea00c6", date: "2026-08-12", author: "Fare Estimator", subject: "feat: enforce Postgres atomicity and history ownership" },
  { hash: "09db0a4", date: "2026-08-12", author: "Fare Estimator", subject: "test: define hybrid retrieval orchestration" },
  { hash: "62244ad", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add bounded hybrid retrieval orchestration" },
  { hash: "9967f33", date: "2026-08-12", author: "Fare Estimator", subject: "test: require rollback-safe versioned card identities" },
  { hash: "1d0a5a8", date: "2026-08-12", author: "Fare Estimator", subject: "fix: preserve cards across corpus versions" },
  { hash: "d5bd874", date: "2026-08-12", author: "Fare Estimator", subject: "test: define Postgres hybrid retrieval behavior" },
  { hash: "c16fca0", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add Postgres exact lexical and vector retrieval" },
  { hash: "db902ec", date: "2026-08-12", author: "Fare Estimator", subject: "test: define semantic cache safety boundaries" },
  { hash: "0b95c4b", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add version-safe Postgres semantic cache" },
  { hash: "b4211a6", date: "2026-08-12", author: "Fare Estimator", subject: "test: define atomic ingestion pipeline order" },
  { hash: "fc567c7", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add idempotent staged ingestion pipeline" },
  { hash: "cb817d4", date: "2026-08-12", author: "Fare Estimator", subject: "test: define corpus documents and immutable snapshots" },
  { hash: "ede43c7", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add versioned corpus builders and GCS snapshots" },
  { hash: "6ae70a2", date: "2026-08-12", author: "Fare Estimator", subject: "test: define concrete Postgres corpus staging" },
  { hash: "2fc9181", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add concrete Postgres corpus staging" },
  { hash: "5c4108a", date: "2026-08-12", author: "Fare Estimator", subject: "test: define ask quota cache and failure ordering" },
  { hash: "39441f7", date: "2026-08-12", author: "Fare Estimator", subject: "feat: orchestrate ask cache retrieval quota and history" },
  { hash: "96775f7", date: "2026-08-12", author: "Fare Estimator", subject: "test: define atomic answer and deletion persistence" },
  { hash: "2e40d84", date: "2026-08-12", author: "Fare Estimator", subject: "feat: atomically persist answers feedback and deletion" },
  { hash: "51df338", date: "2026-08-12", author: "Fare Estimator", subject: "test: define active corpus context and embedding reuse" },
  { hash: "1fdbf92", date: "2026-08-12", author: "Fare Estimator", subject: "feat: bind cache context to active corpus versions" },
  { hash: "6412a82", date: "2026-08-12", author: "Fare Estimator", subject: "test: define production service graph and route boundary" },
  { hash: "7e29999", date: "2026-08-12", author: "Fare Estimator", subject: "feat: wire production API service graph" },
  { hash: "38f7f52", date: "2026-08-12", author: "Fare Estimator", subject: "test: define ingestion job source contracts" },
  { hash: "65a5751", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add scheduled corpus ingestion job" },
  { hash: "1f11505", date: "2026-08-12", author: "Fare Estimator", subject: "test: define API resilience boundaries" },
  { hash: "4fbce54", date: "2026-08-12", author: "Fare Estimator", subject: "test: pin OpenAI runtime observability contract" },
  { hash: "eb454e1", date: "2026-08-12", author: "Fare Estimator", subject: "feat: harden API runtime boundaries" },
  { hash: "79588d3", date: "2026-08-12", author: "Fare Estimator", subject: "test: define content-free answer telemetry" },
  { hash: "df2d4f8", date: "2026-08-12", author: "Fare Estimator", subject: "feat: log content-free answer telemetry" },
  { hash: "27b6ee3", date: "2026-08-12", author: "Fare Estimator", subject: "chore: pass backend quality gates" },
  { hash: "2e487b6", date: "2026-08-12", author: "Fare Estimator", subject: "test: define frontend product contracts" },
  { hash: "cb3be7c", date: "2026-08-12", author: "Fare Estimator", subject: "feat: build authenticated rules desk PWA" },
  { hash: "2ae3726", date: "2026-08-12", author: "Fare Estimator", subject: "test: define browser acceptance contracts" },
  { hash: "e714abe", date: "2026-08-12", author: "Fare Estimator", subject: "test: verify PWA in real browser" },
  { hash: "b42e9ef", date: "2026-08-12", author: "Fare Estimator", subject: "feat: complete production delivery plan" },
  { hash: "b576936", date: "2026-08-12", author: "Fare Estimator", subject: "test: add public route and legal page coverage" },
  { hash: "1bee164", date: "2026-08-12", author: "Fare Estimator", subject: "feat: add public ux and legal pages" },
  { hash: "2addab0", date: "2026-08-12", author: "Fare Estimator", subject: "fix: show login progress state" },
  { hash: "927f844", date: "2026-08-12", author: "Fare Estimator", subject: "test: require luna generation model default" },
  { hash: "cb92681", date: "2026-08-12", author: "Fare Estimator", subject: "fix: switch generation model to luna" },
  { hash: "9a0c28c", date: "2026-08-13", author: "Fare Estimator", subject: "fix: grant API Firebase account deletion permission" },
  { hash: "afe6bcc", date: "2026-08-13", author: "Fare Estimator", subject: "docs: record Firebase IAM integration evidence" },
  { hash: "08bcf1a", date: "2026-08-13", author: "Fare Estimator", subject: "test: require pinned production secret versions" },
  { hash: "deac7ed", date: "2026-08-13", author: "Fare Estimator", subject: "fix: pin production secret versions" },
  { hash: "7a29177", date: "2026-08-13", author: "Fare Estimator", subject: "test: cover Firebase Hosting proxy delivery" },
  { hash: "d7a70b2", date: "2026-08-13", author: "Fare Estimator", subject: "fix: add Firebase Hosting proxy delivery" },
  { hash: "188173c", date: "2026-08-13", author: "Fare Estimator", subject: "test: capture Cloud SQL edition requirement" },
  { hash: "63f12e3", date: "2026-08-13", author: "Fare Estimator", subject: "fix: select supported Cloud SQL edition" },
  { hash: "6eb6428", date: "2026-08-13", author: "Fare Estimator", subject: "fix: restrict Cloud Build upload scope" },
  { hash: "9f7eb6e", date: "2026-08-13", author: "Fare Estimator", subject: "test: cover Cloud Build script upload boundary" },
  { hash: "86e8eab", date: "2026-08-13", author: "Fare Estimator", subject: "fix: retain frontend build scripts in Cloud Build" },
  { hash: "42d0c61", date: "2026-08-13", author: "Fare Estimator", subject: "test: require uploadable Cloud Build policy" },
  { hash: "19e823d", date: "2026-08-13", author: "Fare Estimator", subject: "test: prevent nested Cloud Build ignore includes" },
  { hash: "5f4e8bb", date: "2026-08-13", author: "Fare Estimator", subject: "fix: make Cloud Build upload policy CI-verifiable" },
  { hash: "d2c5d6c", date: "2026-08-13", author: "Fare Estimator", subject: "fix: scope Cloud Build policy test to uploaded source" },
  { hash: "0732836", date: "2026-08-13", author: "Fare Estimator", subject: "test: add Linux visual regression baselines" },
  { hash: "4662847", date: "2026-08-13", author: "Fare Estimator", subject: "test: require migration frontend origin" },
  { hash: "3f74b53", date: "2026-08-13", author: "Fare Estimator", subject: "fix: configure migration job frontend origin" },
  { hash: "9f617e6", date: "2026-08-13", author: "Fare Estimator", subject: "test: reproduce ingestion retry failures" },
  { hash: "82f6d7b", date: "2026-08-13", author: "Fare Estimator", subject: "fix: make corpus ingestion retries safe" },
  { hash: "6177571", date: "2026-08-13", author: "Fare Estimator", subject: "test: require batched ingestion embeddings" },
  { hash: "a45e6a6", date: "2026-08-13", author: "Fare Estimator", subject: "fix: batch corpus embedding requests" },
  { hash: "5b17199", date: "2026-08-13", author: "Fare Estimator", subject: "docs: record ingestion recovery TDD evidence" },
  { hash: "7d56c12", date: "2026-08-13", author: "Fare Estimator", subject: "test: reproduce blank Scryfall ruling comments" },
  { hash: "32e0f52", date: "2026-08-13", author: "Fare Estimator", subject: "fix: ignore blank Scryfall rulings" },
  { hash: "2b61f50", date: "2026-08-13", author: "Fare Estimator", subject: "docs: record rulings import TDD evidence" },
  { hash: "d7bc64f", date: "2026-08-13", author: "Fare Estimator", subject: "test: require bounded ingestion staging" },
  { hash: "5005e52", date: "2026-08-13", author: "Fare Estimator", subject: "fix: bound ingestion staging memory" },
  { hash: "d2ee03a", date: "2026-08-13", author: "Fare Estimator", subject: "docs: record bounded staging TDD evidence" },
  { hash: "7316285", date: "2026-08-13", author: "Fare Estimator", subject: "test: require safe Firebase auth template" },
  { hash: "7be96ae", date: "2026-08-13", author: "Fare Estimator", subject: "feat: add safe Firebase auth deployment config" },
  { hash: "3676dad", date: "2026-08-13", author: "Fare Estimator", subject: "test: require deployed support contact" },
  { hash: "7b91f5a", date: "2026-08-13", author: "Fare Estimator", subject: "fix: publish verified support contact" },
  { hash: "b3288c5", date: "2026-08-13", author: "Fare Estimator", subject: "test: require Firebase cache exclusion" },
  { hash: "4aea7c3", date: "2026-08-13", author: "Fare Estimator", subject: "chore: ignore Firebase deploy cache" },
  { hash: "0854c6c", date: "2026-08-13", author: "Fare Estimator", subject: "test: require automatic PWA release activation" },
  { hash: "16fb230", date: "2026-08-13", author: "Fare Estimator", subject: "fix: activate PWA releases automatically" },
  { hash: "bd44b3a", date: "2026-08-13", author: "Fare Estimator", subject: "docs: record live Firebase integration evidence" },
  { hash: "d2fe2d1", date: "2026-08-13", author: "Fare Estimator", subject: "test: require Cloud Build manifest dependencies" },
  { hash: "3dfe7c2", date: "2026-08-13", author: "Fare Estimator", subject: "fix: upload manifest policy to Cloud Build" },
  { hash: "91dbe73", date: "2026-08-13", author: "Fare Estimator", subject: "docs: normalize integration evidence formatting" },
  { hash: "9f85d68", date: "2026-08-13", author: "Fare Estimator", subject: "test: require actionable client request errors" },
  { hash: "e1da69d", date: "2026-08-13", author: "Fare Estimator", subject: "fix: surface safe client request failures" },
  { hash: "76f6189", date: "2026-08-13", author: "Fare Estimator", subject: "test: require Firebase revocation-read permission" },
  { hash: "d685eaf", date: "2026-08-13", author: "Fare Estimator", subject: "fix: allow Firebase revocation checks" },
  { hash: "4599028", date: "2026-08-13", author: "Fare Estimator", subject: "test: require null-safe dev budget validation" },
  { hash: "675511a", date: "2026-08-13", author: "Fare Estimator", subject: "fix: validate optional dev budget safely" },
  { hash: "61d9c47", date: "2026-08-13", author: "Fare Estimator", subject: "test: require inactive corpus restaging" },
  { hash: "2142cb0", date: "2026-08-13", author: "Fare Estimator", subject: "fix: restage inactive corpus snapshots" },
  { hash: "449f6f3", date: "2026-08-13", author: "Fare Estimator", subject: "test: require canonical ruling deduplication" },
  { hash: "a9b9420", date: "2026-08-13", author: "Fare Estimator", subject: "fix: deduplicate canonical rulings" },
  { hash: "1c90094", date: "2026-08-14", author: "Fare Estimator", subject: "test: require supported ruling filtering" },
  { hash: "c934480", date: "2026-08-14", author: "Fare Estimator", subject: "fix: filter unsupported rulings before embedding" },
  { hash: "ee80157", date: "2026-08-14", author: "Fare Estimator", subject: "test: exclude local terraform plans from builds" },
  { hash: "8c26802", date: "2026-08-14", author: "Fare Estimator", subject: "fix: exclude local terraform plans from builds" },
  { hash: "499b236", date: "2026-08-14", author: "Fare Estimator", subject: "test: reject localhost production API origins" },
  { hash: "f35fcd0", date: "2026-08-14", author: "Fare Estimator", subject: "fix: use same-origin API in production" },
  { hash: "23e3e42", date: "2026-08-14", author: "Fare Estimator", subject: "test: require exact glossary term retrieval" },
  { hash: "ba9165e", date: "2026-08-14", author: "Fare Estimator", subject: "fix: retrieve mentioned glossary terms exactly" },
  { hash: "f59f2ac", date: "2026-08-14", author: "Fare Estimator", subject: "test: require hosted health proxy" },
  { hash: "bc92528", date: "2026-08-14", author: "Fare Estimator", subject: "fix: proxy hosted health checks" },
  { hash: "264ba24", date: "2026-08-14", author: "Fare Estimator", subject: "test: require base-path Firebase health glob" },
  { hash: "6877a7e", date: "2026-08-14", author: "Fare Estimator", subject: "fix: match hosted health base path" },
  { hash: "f25415c", date: "2026-08-14", author: "Fare Estimator", subject: "test: require explicit health route regex" },
  { hash: "d3f6615", date: "2026-08-14", author: "Fare Estimator", subject: "fix: proxy exact hosted health path" },
  { hash: "2baa874", date: "2026-08-14", author: "Fare Estimator", subject: "docs: clarify health probe boundary" },
  { hash: "b8d96f0", date: "2026-08-14", author: "Fare Estimator", subject: "docs: record integration lessons and live evidence" },
  { hash: "d7b6b7b", date: "2026-08-14", author: "Fare Estimator", subject: "docs: normalize integration evidence encoding" },
  { hash: "182f3ae", date: "2026-08-14", author: "Fare Estimator", subject: "test: define navigation and SEO contracts" },
  { hash: "44290dc", date: "2026-08-14", author: "Fare Estimator", subject: "feat: refine responsive desk navigation" },
  { hash: "ac45891", date: "2026-08-14", author: "Fare Estimator", subject: "docs: record frontend integration lessons" },
  { hash: "06a0f9d", date: "2026-08-14", author: "Fare Estimator", subject: "docs: move plans under docs" },
  { hash: "f94e8c2", date: "2026-08-14", author: "Fare Estimator", subject: "test: reproduce Firebase sign-in loop" },
  { hash: "24cefcc", date: "2026-08-14", author: "Fare Estimator", subject: "fix: keep Firebase sign-in callbacks same-origin" },
  { hash: "6e5f5c0", date: "2026-08-14", author: "Fare Estimator", subject: "test: reproduce auth and logout route outcomes" },
  { hash: "85987d6", date: "2026-08-14", author: "Fare Estimator", subject: "fix: route auth and logout to intended screens" },
  { hash: "1951679", date: "2026-08-14", author: "Fare Estimator", subject: "test: require direct auth from the first screen" },
  { hash: "7c39f2a", date: "2026-08-14", author: "Fare Estimator", subject: "refactor: invoke Firebase auth from public screens" },
  { hash: "247157d", date: "2026-08-14", author: "Fare Estimator", subject: "docs: record direct auth deployment evidence" },
  { hash: "c9f3490", date: "2026-08-14", author: "Fare Estimator", subject: "test: capture live OAuth redirect mismatch" },
  { hash: "0361efb", date: "2026-08-14", author: "Fare Estimator", subject: "docs: distinguish OAuth callback allowlists" },
  { hash: "6f590c7", date: "2026-08-14", author: "Fare Estimator", subject: "fix: complete OAuth redirect recovery" },
  { hash: "8b00bfe", date: "2026-08-15", author: "Fare Estimator", subject: "docs: consolidate product and architecture guides" },
  { hash: "b025225", date: "2026-08-17", author: "Fare Estimator", subject: "test: add privacy policy content expectations" },
  { hash: "c92a40d", date: "2026-08-17", author: "Fare Estimator", subject: "feat: publish implementation-aligned privacy policy" },
  { hash: "e94d678", date: "2026-08-17", author: "Fare Estimator", subject: "docs: record privacy policy verification" },
  { hash: "0c45a02", date: "2026-08-17", author: "Fare Estimator", subject: "test: define SEO metadata and crawler contracts" },
  { hash: "cf33213", date: "2026-08-17", author: "Fare Estimator", subject: "feat: generate production-safe SEO metadata" },
  { hash: "b843c37", date: "2026-08-17", author: "Fare Estimator", subject: "docs: record SEO verification" },
  { hash: "89cafe6", date: "2026-08-19", author: "Fare Estimator", subject: "test(ui): define command desk interaction contract" },
  { hash: "db368a2", date: "2026-08-19", author: "Fare Estimator", subject: "feat(ui): build single-screen rules command desk" },
  { hash: "e69861a", date: "2026-08-19", author: "Fare Estimator", subject: "test(ui): verify responsive command desk preview" },
  { hash: "92208b2", date: "2026-08-19", author: "Fare Estimator", subject: "test: add warm sign-in and install dismissal reproducers" },
  { hash: "ac9dbae", date: "2026-08-19", author: "Fare Estimator", subject: "feat: implement warm sign-in and dismissible install prompt" },
  { hash: "70d637d", date: "2026-08-19", author: "Fare Estimator", subject: "test: enforce warm PWA brand assets" },
  { hash: "39dc022", date: "2026-08-19", author: "Fare Estimator", subject: "feat: align favicon and PWA assets with warm brand" },
  { hash: "604dfb2", date: "2026-08-19", author: "Fare Estimator", subject: "test: finalize warm sign-in verification" },
  { hash: "7c612c8", date: "2026-08-19", author: "Fare Estimator", subject: "docs: record warm preview deployment" },
  { hash: "af73877", date: "2026-08-19", author: "Zylush", subject: "Merge pull request #1 from zylush/preview/single-screen-rag-desk" },
  { hash: "f36522d", date: "2026-08-25", author: "Fare Estimator", subject: "feat: qualify development rules desk release" },
  { hash: "2b67108", date: "2026-08-25", author: "Fare Estimator", subject: "test: add chat history continuation journeys" },
  { hash: "e2494e3", date: "2026-08-25", author: "Fare Estimator", subject: "feat: add resumable chat history desk" },
  { hash: "2faa893", date: "2026-08-25", author: "Fare Estimator", subject: "refactor: refine responsive chat history layout" },
  { hash: "3e50395", date: "2026-08-25", author: "Fare Estimator", subject: "docs: record chat history verification checkpoints" },
  { hash: "131f036", date: "2026-08-25", author: "Fare Estimator", subject: "docs: add complete patch history" },
  { hash: "4b1479c", date: "2026-08-25", author: "Fare Estimator", subject: "test: define website patch history journey" },
  { hash: "76ae629", date: "2026-08-25", author: "Fare Estimator", subject: "feat: publish concise website patch history" },
  { hash: "f3f28b7", date: "2026-08-25", author: "Fare Estimator", subject: "test: define patch history compaction controls" },
  { hash: "8251f6e", date: "2026-08-25", author: "Fare Estimator", subject: "feat: compact and sort patch history dates" },
]
